apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: sikp
type: Opaque
stringData:
  DB_PASSWORD: "260605"
  JWT_SECRET: "belajar-kubernetes-dummy-secret"
  OAUTH_STATE_SECRET: "belajar-kubernetes-dummy-secret"
  MINIO_ROOT_PASSWORD: "sikpgacor123#"
